/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsClassifyContext {
  cwd?: string
  projectRoot?: string
  homeDir?: string
  protectedPaths?: Array<string>
  shell?: string
}
export declare function classify(command: string, context?: JsClassifyContext | undefined | null): any
export declare function riskScore(command: string): number
export declare function riskLevel(command: string): string
export declare function classifyBatch(commands: Array<string>, context?: JsClassifyContext | undefined | null): Array<any>
